import { type CompanyRawEntry, KNOWN_COMPANIES } from "./company-data";

export const ALL_COMPANIES: CompanyRawEntry[] = [
  ...KNOWN_COMPANIES,
  // 101 - 150
  { name_he: "ורביט (Verbit)", name_en: "Verbit", aliases: ["Verbit.ai", "ורביט"], website_domain: "verbit.ai", category: "hitech" },
  { name_he: "ורוניס", name_en: "Varonis", aliases: ["Varonis Systems", "ורוניס מערכות"], website_domain: "varonis.com", category: "hitech" },
  { name_he: "חברת החשמל לישראל", name_en: "Israel Electric Corporation", aliases: ["חברת החשמל", "חח\"י", "IEC"], website_domain: "iec.co.il", category: "government" },
  { name_he: "טאבולה", name_en: "Taboola", aliases: ["Taboola"], website_domain: "taboola.com", category: "hitech" },
  { name_he: "טאואר סמיקונדקטור", name_en: "Tower Semiconductor", aliases: ["TowerJazz", "טאואר ג'אז"], website_domain: "towersemi.com", category: "hitech" },
  { name_he: "טבע תעשיות פרמצבטיות", name_en: "Teva Pharmaceuticals", aliases: ["טבע", "Teva"], website_domain: "teva.co.il", category: "health" },
  { name_he: "טיפאניק", name_en: "Tipanic", aliases: [], website_domain: "", category: "other", uncertain_domain: true },
  { name_he: "טיפטילטי (Tipalti)", name_en: "Tipalti", aliases: ["Tipalti", "טיפלתי"], website_domain: "tipalti.com", category: "hitech" },
  { name_he: "טלדור", name_en: "Taldor", aliases: ["טלדור מערכות", "One Taldor"], website_domain: "one1.co.il", category: "hitech", parent_name_he: "וואן טכנולוגיות" },
  { name_he: "טריפל סי", name_en: "Triple C", aliases: ["Triple C Cloud", "טריפל סי מחשוב בענן"], website_domain: "triplec.co.il", category: "hitech" },
  { name_he: "טרנזמיט סקיוריטי", name_en: "Transmit Security", aliases: ["Transmit Security"], website_domain: "transmitsecurity.com", category: "hitech" },
  { name_he: "יבמ ישראל", name_en: "IBM Israel", aliases: ["IBM", "יבמ"], website_domain: "ibm.com", category: "hitech" },
  { name_he: "יד שרה", name_en: "Yad Sarah", aliases: ["ארגון יד שרה"], website_domain: "yadsarah.org.il", category: "health" },
  { name_he: "יוחננוף", name_en: "Yohananof", aliases: ["רשת יוחננוף"], website_domain: "yochananof.co.il", category: "other" },
  { name_he: "יוטפו", name_en: "Yotpo", aliases: ["Yotpo"], website_domain: "yotpo.com", category: "hitech" },
  { name_he: "יוניליוור ישראל", name_en: "Unilever Israel", aliases: ["Unilever", "יוניליוור"], website_domain: "unilever.co.il", category: "other" },
  { name_he: "יס (yes)", name_en: "yes DBS", aliases: ["yes", "חברת יס", "די בי אס"], website_domain: "yes.co.il", category: "other", parent_name_he: "בזק" },
  { name_he: "יש חסד", name_en: "Yesh Chesed", aliases: ["יש בשכונה", "רשת יש"], website_domain: "shufersal.co.il", category: "other", parent_name_he: "שופרסל" },
  { name_he: "ישראייר", name_en: "Israir Airlines", aliases: ["Israir"], website_domain: "israir.co.il", category: "other" },
  { name_he: "ישראכרט", name_en: "Isracard", aliases: ["קבוצת ישראכרט"], website_domain: "isracard.co.il", category: "banking" },
  { name_he: "כלל ביטוח", name_en: "Clal Insurance", aliases: ["כלל ביטוח ופיננסים", "Clal"], website_domain: "clalbit.co.il", category: "banking" },
  { name_he: "כללית שירותי בריאות", name_en: "Clalit Health Services", aliases: ["כללית", "קופת חולים כללית"], website_domain: "clalit.co.il", category: "health" },
  { name_he: "לאומית שירותי בריאות", name_en: "Leumit Health Services", aliases: ["לאומית", "קופת חולים לאומית"], website_domain: "leumit.co.il", category: "health" },
  { name_he: "לוגז.איי או", name_en: "Logz.io", aliases: ["Logz.io", "לוגז"], website_domain: "logz.io", category: "hitech" },
  { name_he: "לומניס", name_en: "Lumenis", aliases: ["Lumenis"], website_domain: "lumenis.com", category: "health" },
  { name_he: "למונייד", name_en: "Lemonade", aliases: ["Lemonade Insurance"], website_domain: "lemonade.com", category: "hitech" },
  { name_he: "מאנדיי", name_en: "monday.com", aliases: ["Monday", "מאנדיי.קום"], website_domain: "monday.com", category: "hitech" },
  { name_he: "מגדל ביטוח", name_en: "Migdal Insurance", aliases: ["מגדל", "Migdal"], website_domain: "migdal.co.il", category: "banking" },
  { name_he: "מגן דוד אדום", name_en: "Magen David Adom", aliases: ["מד\"א", "MDA"], website_domain: "mdais.org", category: "health" },
  { name_he: "מדיטרוניק ישראל", name_en: "Medtronic Israel", aliases: ["Medtronic", "מדיטרוניק"], website_domain: "medtronic.com", category: "health" },
  { name_he: "מוביט", name_en: "Moovit", aliases: ["Moovit", "Moovit Intel"], website_domain: "moovitapp.com", category: "hitech" },
  { name_he: "מובילאיי", name_en: "Mobileye", aliases: ["Mobileye", "Mobileye Intel"], website_domain: "mobileye.com", category: "hitech" },
  { name_he: "מטא ישראל", name_en: "Meta Israel", aliases: ["Meta", "Facebook Israel", "פייסבוק"], website_domain: "meta.com", category: "hitech" },
  { name_he: "מטריקס", name_en: "Matrix IT", aliases: ["Matrix", "מטריקס אי טי"], website_domain: "matrix.co.il", category: "hitech" },
  { name_he: "מטריקס אינטגרה", name_en: "Matrix Integra", aliases: ["אינטגרה", "Matrix IFS"], website_domain: "matrix.co.il", category: "hitech", parent_name_he: "מטריקס" },
  { name_he: "מיקרוסופט ישראל", name_en: "Microsoft Israel", aliases: ["Microsoft", "מיקרוסופט"], website_domain: "microsoft.com", category: "hitech" },
  { name_he: "מיקרופוקוס ישראל", name_en: "Micro Focus Israel", aliases: ["Micro Focus", "OpenText"], website_domain: "opentext.com", category: "hitech" },
  { name_he: "מכבי שירותי בריאות", name_en: "Maccabi Healthcare Services", aliases: ["מכבי", "קופת חולים מכבי"], website_domain: "maccabi4u.co.il", category: "health" },
  { name_he: "מכון ויצמן למדע", name_en: "Weizmann Institute of Science", aliases: ["מכון ויצמן", "Weizmann"], website_domain: "weizmann.ac.il", category: "education" },
  { name_he: "מכללת הדסה", name_en: "Hadassah Academic College", aliases: ["HAC", "המכללה האקדמית הדסה"], website_domain: "hac.ac.il", category: "education" },
  { name_he: "מכללת מבחר", name_en: "Mivchar College", aliases: ["מבחר", "מכללת מבח\"ר"], website_domain: "mivchar.org.il", category: "education" },
  { name_he: "מלאנוקס (אנבידיה)", name_en: "Mellanox Technologies", aliases: ["Mellanox", "מלאנוקס", "NVIDIA Networking"], website_domain: "nvidia.com", category: "hitech", parent_name_he: "אנבידיה ישראל" },
  { name_he: "מליו (Melio)", name_en: "Melio", aliases: ["Melio Payments", "מליו"], website_domain: "meliopayments.com", category: "hitech" },
  { name_he: "מליסרון", name_en: "Melisron", aliases: ["קניוני עופר", "Melisron"], website_domain: "melisron.co.il", category: "other" },
  { name_he: "מלם תים", name_en: "Malam Team", aliases: ["מלם", "תים", "MalamTeam"], website_domain: "malamteam.com", category: "hitech" },
  { name_he: "מנורה מבטחים", name_en: "Menora Mivtachim", aliases: ["מנורה", "Menora"], website_domain: "menoramivt.co.il", category: "banking" },
  { name_he: "מנפאואר ישראל", name_en: "Manpower Israel", aliases: ["Manpower", "מנפאואר"], website_domain: "manpower.co.il", category: "other" },
  { name_he: "מערך הדיגיטל הלאומי", name_en: "National Digital Directorate", aliases: ["ממשל זמין", "Gov.il"], website_domain: "gov.il", category: "government" },
  { name_he: "מפתח (מרכזי הכוון תעסוקתי)", name_en: "Mafteach Career Centers", aliases: ["מפתח", "הכוון תעסוקתי לחרדים"], website_domain: "mafteach.org.il", category: "education" },
  { name_he: "מקורות", name_en: "Mekorot", aliases: ["חברת מקורות"], website_domain: "mekorot.co.il", category: "government" },

  // 151 - 200
  { name_he: "מקס איט פיננסים", name_en: "Max IT Finance", aliases: ["Max", "לאומי קארד", "מקס"], website_domain: "max.co.il", category: "banking" },
  { name_he: "משרד האוצר", name_en: "Ministry of Finance", aliases: ["אגף החשב הכללי", "רשות המסים"], website_domain: "gov.il", category: "government" },
  { name_he: "משרד הבריאות", name_en: "Ministry of Health", aliases: ["משה\"ב"], website_domain: "gov.il", category: "government" },
  { name_he: "משרד החינוך", name_en: "Ministry of Education", aliases: ["משה\"ח"], website_domain: "gov.il", category: "government" },
  { name_he: "משרד הכלכלה", name_en: "Ministry of Economy and Industry", aliases: ["משרד הכלכלה והתעשייה"], website_domain: "gov.il", category: "government" },
  { name_he: "משרד המשפטים", name_en: "Ministry of Justice", aliases: ["רשות התאגידים", "הטאבו"], website_domain: "gov.il", category: "government" },
  { name_he: "נו ניים סקיוריטי", name_en: "Noname Security", aliases: ["Noname Security", "Akamai Noname"], website_domain: "nonamesecurity.com", category: "hitech" },
  { name_he: "נובה מכשירי מדידה", name_en: "Nova Measuring Instruments", aliases: ["Nova", "נובה"], website_domain: "novami.com", category: "hitech" },
  { name_he: "נמלי ישראל", name_en: "Israel Ports Company", aliases: ["חברת נמלי ישראל", "חנ\"י"], website_domain: "israports.co.il", category: "government" },
  { name_he: "נס טכנולוגיות", name_en: "Ness Technologies", aliases: ["Ness", "נס"], website_domain: "ness.com", category: "hitech" },
  { name_he: "נקסט אינשורנס", name_en: "Next Insurance", aliases: ["Next Insurance"], website_domain: "nextinsurance.com", category: "hitech" },
  { name_he: "סאפ ישראל", name_en: "SAP Israel", aliases: ["SAP", "סאפ"], website_domain: "sap.com", category: "hitech" },
  { name_he: "סולאראדג", name_en: "SolarEdge Technologies", aliases: ["SolarEdge", "סולאראדג'"], website_domain: "solaredge.com", category: "hitech" },
  { name_he: "סופרבוס", name_en: "Superbus", aliases: ["Superbus"], website_domain: "superbus.co.il", category: "other" },
  { name_he: "סטרטאפ ניישן סנטרל", name_en: "Start-Up Nation Central", aliases: ["SNC", "סטארט-אפ ניישן"], website_domain: "startupnationcentral.org", category: "other" },
  { name_he: "סיוה (CEVA)", name_en: "CEVA DSP", aliases: ["CEVA", "סיוה"], website_domain: "ceva-dsp.com", category: "hitech" },
  { name_he: "סייברארק", name_en: "CyberArk", aliases: ["CyberArk"], website_domain: "cyberark.com", category: "hitech" },
  { name_he: "סיילספורס ישראל", name_en: "Salesforce Israel", aliases: ["Salesforce", "סיילספורס"], website_domain: "salesforce.com", category: "hitech" },
  { name_he: "סימילרווב", name_en: "Similarweb", aliases: ["Similarweb"], website_domain: "similarweb.com", category: "hitech" },
  { name_he: "סימנס ישראל", name_en: "Siemens Israel", aliases: ["Siemens", "סימנס"], website_domain: "siemens.com", category: "hitech" },
  { name_he: "סינמדיה", name_en: "Synamedia", aliases: ["Synamedia", "NDS"], website_domain: "synamedia.com", category: "hitech" },
  { name_he: "סיסקו ישראל", name_en: "Cisco Israel", aliases: ["Cisco", "סיסקו"], website_domain: "cisco.com", category: "hitech" },
  { name_he: "סלקום", name_en: "Cellcom Israel", aliases: ["Cellcom", "סלקום ישראל"], website_domain: "cellcom.co.il", category: "other" },
  { name_he: "סלקום עסקים", name_en: "Cellcom Business", aliases: ["סלקום פתרונות תקשורת"], website_domain: "cellcom.co.il", category: "other", parent_name_he: "סלקום" },
  { name_he: "סנו", name_en: "Sano", aliases: ["סנו מפעלי ברונוס"], website_domain: "sano.co.il", category: "other" },
  { name_he: "סנטינל וואן", name_en: "SentinelOne", aliases: ["SentinelOne", "סנטינלוואן"], website_domain: "sentinelone.com", category: "hitech" },
  { name_he: "סניק (Snyk)", name_en: "Snyk", aliases: ["Snyk", "סניק"], website_domain: "snyk.io", category: "hitech" },
  { name_he: "ספוט אוטומציה", name_en: "Spot by NetApp", aliases: ["Spotinst", "Spot"], website_domain: "spot.io", category: "hitech" },
  { name_he: "סרגון נטוורקס", name_en: "Ceragon Networks", aliases: ["Ceragon"], website_domain: "ceragon.com", category: "hitech" },
  { name_he: "עזר מציון", name_en: "Ezer Mizion", aliases: ["עזר מציון"], website_domain: "ami.org.il", category: "health" },
  { name_he: "עזריאלי מכללה להנדסה", name_en: "Azrieli College of Engineering Jerusalem", aliases: ["מכללת עזריאלי"], website_domain: "jce.ac.il", category: "education" },
  { name_he: "עיריית אשדוד", name_en: "Ashdod Municipality", aliases: ["עיריית אשדוד"], website_domain: "ashdod.muni.il", category: "government" },
  { name_he: "עיריית בני ברק", name_en: "Bnei Brak Municipality", aliases: ["עיריית בני ברק"], website_domain: "bnei-brak.muni.il", category: "government" },
  { name_he: "עיריית חיפה", name_en: "Haifa Municipality", aliases: ["עיריית חיפה"], website_domain: "haifa.muni.il", category: "government" },
  { name_he: "עיריית ירושלים", name_en: "Jerusalem Municipality", aliases: ["עיריית ירושלים"], website_domain: "jerusalem.muni.il", category: "government" },
  { name_he: "עיריית פתח תקווה", name_en: "Petah Tikva Municipality", aliases: ["עיריית פ\"ת"], website_domain: "petah-tikva.muni.il", category: "government" },
  { name_he: "עיריית תל אביב-יפו", name_en: "Tel Aviv-Yafo Municipality", aliases: ["עיריית ת\"א"], website_domain: "tel-aviv.gov.il", category: "government" },
  { name_he: "עמותת תכלית", name_en: "Tachlit NGO", aliases: ["תכלית"], website_domain: "tachlit.org.il", category: "other" },
  { name_he: "עשת לפידות", name_en: "Eshet Lapidot", aliases: ["Eshet Tours", "עשת טורס"], website_domain: "eshet.com", category: "other" },
  { name_he: "פאלו אלטו נטוורקס", name_en: "Palo Alto Networks", aliases: ["Palo Alto Networks Israel"], website_domain: "paloaltonetworks.com", category: "hitech" },
  { name_he: "פאפאיה גלובל", name_en: "Papaya Global", aliases: ["Papaya Global", "פאפאיה"], website_domain: "papayaglobal.com", category: "hitech" },
  { name_he: "פורטר", name_en: "Forter", aliases: ["Forter Fraud Prevention"], website_domain: "forter.com", category: "hitech" },
  { name_he: "פיבר", name_en: "Fyber", aliases: ["Fyber", "Digital Turbine Fyber"], website_domain: "digitalturbine.com", category: "hitech" },
  { name_he: "פיוניר", name_en: "Payoneer", aliases: ["Payoneer", "פיוניר ישראל"], website_domain: "payoneer.com", category: "hitech" },
  { name_he: "פיוניר פיתוח", name_en: "Payoneer R&D", aliases: ["Payoneer Development"], website_domain: "payoneer.com", category: "hitech", parent_name_he: "פיוניר" },
  { name_he: "פייבר", name_en: "Fiverr", aliases: ["Fiverr", "פייבר"], website_domain: "fiverr.com", category: "hitech" },
  { name_he: "פיליפס ישראל", name_en: "Philips Israel", aliases: ["Philips", "פיליפס מדיקל"], website_domain: "philips.co.il", category: "health" },
  { name_he: "פלאפון", name_en: "Pelephone Communications", aliases: ["Pelephone", "פלאפון תקשורת"], website_domain: "pelephone.co.il", category: "other", parent_name_he: "בזק" },
  { name_he: "פלייבאז", name_en: "Playbuzz (Ex.co)", aliases: ["Playbuzz", "Ex.co"], website_domain: "ex.co", category: "hitech" },
  { name_he: "פלייטיקה", name_en: "Playtika", aliases: ["Playtika"], website_domain: "playtika.com", category: "hitech" },

  // 201 - 236
  { name_he: "פעמונים", name_en: "Paamonim", aliases: ["ארגון פעמונים"], website_domain: "paamonim.org", category: "other" },
  { name_he: "פרטנר תקשורת", name_en: "Partner Communications", aliases: ["Partner", "פרטנר", "אורנג'"], website_domain: "partner.co.il", category: "other" },
  { name_he: "פריון נטוורק", name_en: "Perion Network", aliases: ["Perion"], website_domain: "perion.com", category: "hitech" },
  { name_he: "פריסמה פוטו", name_en: "Prisma Photo", aliases: [], website_domain: "", category: "other", uncertain_domain: true },
  { name_he: "צק פוינט", name_en: "Check Point Software Technologies", aliases: ["Check Point", "צ'ק פוינט"], website_domain: "checkpoint.com", category: "hitech" },
  { name_he: "צקמרקס", name_en: "Checkmarx", aliases: ["Checkmarx", "צ'קמרקס"], website_domain: "checkmarx.com", category: "hitech" },
  { name_he: "קבוצת אשטרום", name_en: "Ashtrom Group", aliases: ["אשטרום", "Ashtrom"], website_domain: "ashtrom.co.il", category: "other" },
  { name_he: "קבוצת עזריאלי", name_en: "Azrieli Group", aliases: ["עזריאלי", "Azrieli"], website_domain: "azrieligroup.com", category: "other" },
  { name_he: "קבוצת שפיר הנדסה", name_en: "Shapir Engineering", aliases: ["שפיר הנדסה", "Shapir"], website_domain: "shapir.co.il", category: "other" },
  { name_he: "קווים תחבורה ציבורית", name_en: "Kavim Public Transportation", aliases: ["קווים"], website_domain: "kavim-t.co.il", category: "other" },
  { name_he: "קומפיוטר אסושיאייטס", name_en: "CA Technologies (Broadcom)", aliases: ["CA Technologies", "קומפיוטר אסושיאייטס ישראל"], website_domain: "broadcom.com", category: "hitech" },
  { name_he: "קונטרולאפ", name_en: "ControlUp", aliases: ["ControlUp"], website_domain: "controlup.com", category: "hitech" },
  { name_he: "קופת חולים מאוחדת", name_en: "Meuhedet Health Services", aliases: ["מאוחדת", "קופ\"ח מאוחדת"], website_domain: "meuhedet.co.il", category: "health" },
  { name_he: "קורלוגיקס", name_en: "Coralogix", aliases: ["Coralogix"], website_domain: "coralogix.com", category: "hitech" },
  { name_he: "קייטוס", name_en: "Kaitos", aliases: [], website_domain: "", category: "other", uncertain_domain: true },
  { name_he: "קלארוויי", name_en: "Claroty", aliases: ["Claroty", "קלארוטי"], website_domain: "claroty.com", category: "hitech" },
  { name_he: "קלרנה ישראל", name_en: "Klarna Israel", aliases: ["Klarna"], website_domain: "klarna.com", category: "hitech" },
  { name_he: "קמטק", name_en: "Camtek", aliases: ["Camtek Ltd", "קמטק בע\"מ"], website_domain: "camtek.com", category: "hitech" },
  { name_he: "קמינריו", name_en: "Kaminario (Silk)", aliases: ["Kaminario", "Silk Cloud"], website_domain: "silk.us", category: "hitech" },
  { name_he: "קרן קמח", name_en: "Kemach Foundation", aliases: ["קמח", "קידום מקצועי חרדי"], website_domain: "kemach.org", category: "education" },
  { name_he: "ראפיד", name_en: "Rapyd", aliases: ["Rapyd Financial", "ראפיד פייננשל"], website_domain: "rapyd.net", category: "hitech" },
  { name_he: "רב קו אונליין", name_en: "Rav-Kav Online", aliases: ["רב-קו אונליין", "Pango Rav Kav"], website_domain: "ravkavonline.co.il", category: "other" },
  { name_he: "רד תקשורת", name_en: "RAD Data Communications", aliases: ["RAD", "רד", "קבוצת רד"], website_domain: "rad.com", category: "hitech" },
  { name_he: "רדוור", name_en: "Radware", aliases: ["Radware"], website_domain: "radware.com", category: "hitech" },
  { name_he: "רילוקו", name_en: "Reloco", aliases: [], website_domain: "", category: "other", uncertain_domain: true },
  { name_he: "ריסקיפייד", name_en: "Riskified", aliases: ["Riskified"], website_domain: "riskified.com", category: "hitech" },
  { name_he: "רכבת ישראל", name_en: "Israel Railways", aliases: ["רכבת"], website_domain: "rail.co.il", category: "government" },
  { name_he: "רמי לוי שיווק השקמה", name_en: "Rami Levy Shivuk Hashikma", aliases: ["רמי לוי", "Rami Levy"], website_domain: "rami-levy.co.il", category: "other" },
  { name_he: "רפאל", name_en: "Rafael Advanced Defense Systems", aliases: ["רפאל מערכות לחימה", "Rafael"], website_domain: "rafael.co.il", category: "hitech" },
  { name_he: "רשות המסים בישראל", name_en: "Israel Tax Authority", aliases: ["רשות המסים", "מס הכנסה"], website_domain: "gov.il", category: "government" },
  { name_he: "רשות שדות התעופה", name_en: "Israel Airports Authority", aliases: ["רש\"ת", "IAA"], website_domain: "iaa.gov.il", category: "government" },
  { name_he: "שופרסל", name_en: "Shufersal", aliases: ["שופרסל שלי", "שופרסל דיל", "Shufersal Group"], website_domain: "shufersal.co.il", category: "other" },
  { name_he: "שטראוס גרופ", name_en: "Strauss Group", aliases: ["שטראוס", "Strauss", "עלית"], website_domain: "strauss-group.com", category: "other" },
  { name_he: "שיכון ובינוי", name_en: "Shikun & Binui", aliases: ["שיכון ובינוי סולל בונה"], website_domain: "shikunbinui.com", category: "other" },
  { name_he: "תים מחשבים", name_en: "Team Computers", aliases: ["תים", "מלם תים מחשבים"], website_domain: "malamteam.com", category: "hitech", parent_name_he: "מלם תים" },
  { name_he: "תנובה", name_en: "Tnuva", aliases: ["קבוצת תנובה"], website_domain: "tnuva.co.il", category: "other" },
];
