// Pre-mapping definitions for Israeli companies in Hebrew
export interface CompanyRawEntry {
  name_he: string;
  name_en?: string;
  aliases?: string[];
  website_domain?: string;
  category: "hitech" | "government" | "banking" | "health" | "education" | "other";
  parent_name_he?: string;
  uncertain_domain?: boolean;
}

export const KNOWN_COMPANIES: CompanyRawEntry[] = [
  { name_he: "אאוטבריין", name_en: "Outbrain", aliases: ["Outbrain"], website_domain: "outbrain.com", category: "hitech" },
  { name_he: "אביב מערכות", name_en: "Aviv Systems", aliases: ["Aviv Group", "אביב ניהול"], website_domain: "avivsystems.co.il", category: "hitech" },
  { name_he: "אגד", name_en: "Egged", aliases: ["Egged"], website_domain: "egged.co.il", category: "other" },
  { name_he: "אובר ישראל", name_en: "Uber Israel", aliases: ["Uber", "אובר"], website_domain: "uber.com", category: "hitech" },
  { name_he: "אודיוקודס", name_en: "AudioCodes", aliases: ["AudioCodes"], website_domain: "audiocodes.com", category: "hitech" },
  { name_he: "אוניברסיטת בן-גוריון", name_en: "Ben-Gurion University", aliases: ["BGU", "בן גוריון"], website_domain: "bgu.ac.il", category: "education" },
  { name_he: "אוניברסיטת בר-אילן", name_en: "Bar-Ilan University", aliases: ["BIU", "בר אילן"], website_domain: "biu.ac.il", category: "education" },
  { name_he: "אוניברסיטת חיפה", name_en: "University of Haifa", aliases: ["Haifa University"], website_domain: "haifa.ac.il", category: "education" },
  { name_he: "אוניברסיטת תל אביב", name_en: "Tel Aviv University", aliases: ["TAU", "תל אביב"], website_domain: "tau.ac.il", category: "education" },
  { name_he: "אופטימוב", name_en: "Optimove", aliases: ["Optimove"], website_domain: "optimove.com", category: "hitech" },
  { name_he: "אורבוטק", name_en: "Orbotech", aliases: ["Orbotech", "KLA Orbotech"], website_domain: "orbotech.com", category: "hitech" },
  { name_he: "אוריבי (ביזאבו)", name_en: "Oribi (Bizzabo)", aliases: ["Oribi", "Bizzabo", "אוריבי", "ביזאבו"], website_domain: "bizzabo.com", category: "hitech" },
  { name_he: "אורקה סקיוריטי", name_en: "Orca Security", aliases: ["Orca Security", "Orca"], website_domain: "orca.security", category: "hitech" },
  { name_he: "אורקל ישראל", name_en: "Oracle Israel", aliases: ["Oracle", "אורקל"], website_domain: "oracle.com", category: "hitech" },
  { name_he: "אושר עד", name_en: "Osher Ad", aliases: ["Osher Ad"], website_domain: "osherad.co.il", category: "other" },
  { name_he: "אחוות תורה", name_en: "Achvat Torah", aliases: ["Achvat Torah"], website_domain: "achvattorah.org", category: "education" },
  { name_he: "אי סי איי טלקום", name_en: "ECI Telecom", aliases: ["ECI", "Ribbon"], website_domain: "ecitele.com", category: "hitech" },
  { name_he: "איזיציפ", name_en: "EZchip", aliases: ["EZchip", "Mellanox EZchip"], website_domain: "", category: "hitech", uncertain_domain: true },
  { name_he: "איחוד הצלה", name_en: "United Hatzalah", aliases: ["United Hatzalah"], website_domain: "1221.org.il", category: "health" },
  { name_he: "איטמר מדיקל", name_en: "Itamar Medical", aliases: ["Itamar Medical", "ZOLL Itamar"], website_domain: "itamar-medical.com", category: "health" },
  { name_he: "איי בי מיוזיק", name_en: "IB Music", aliases: ["IB Music"], website_domain: "", category: "other", uncertain_domain: true },
  { name_he: "אייר בי אנד בי ישראל", name_en: "Airbnb Israel", aliases: ["Airbnb", "איירבנב"], website_domain: "airbnb.com", category: "hitech" },
  { name_he: "איירונסורס", name_en: "ironSource", aliases: ["ironSource", "Unity ironSource"], website_domain: "is.com", category: "hitech" },
  { name_he: "אילקס מדיקל", name_en: "Ilex Medical", aliases: ["Ilex Medical"], website_domain: "ilexmedical.com", category: "health" },
  { name_he: "אינטל ישראל", name_en: "Intel Israel", aliases: ["Intel", "אינטל"], website_domain: "intel.com", category: "hitech" },
  { name_he: "אינטרסלייס", name_en: "Interslice", aliases: [], website_domain: "", category: "hitech", uncertain_domain: true },
  { name_he: "אינסייטק", name_en: "Insightec", aliases: ["Insightec"], website_domain: "insightec.com", category: "health" },
  { name_he: "אל על נתיבי אוויר לישראל", name_en: "El Al", aliases: ["אל על", "El Al Airlines"], website_domain: "elal.com", category: "other" },
  { name_he: "אלביט מערכות", name_en: "Elbit Systems", aliases: ["Elbit", "אלביט"], website_domain: "elbitsystems.com", category: "hitech" },
  { name_he: "אלדין שירותי תוכנה", name_en: "Aladdin Knowledge Systems", aliases: ["Aladdin", "SafeNet"], website_domain: "", category: "hitech", uncertain_domain: true },
  { name_he: "אלוט תקשורת", name_en: "Allot Communications", aliases: ["Allot", "אלוט"], website_domain: "allot.com", category: "hitech" },
  { name_he: "אלעד מערכות", name_en: "Elad Systems", aliases: ["Elad Software", "אלעד תוכנה"], website_domain: "elad.co.il", category: "hitech" },
  { name_he: "אלקטרה אפיקים", name_en: "Electra Afikim", aliases: ["אפיקים תחבורה", "Afikim"], website_domain: "afikim-t.co.il", category: "other", parent_name_he: "אלקטרה בעמ" },
  { name_he: "אלקטרה בעמ", name_en: "Electra Ltd", aliases: ["קבוצת אלקטרה", "Electra"], website_domain: "electra.co.il", category: "other" },
  { name_he: "אמדוקס", name_en: "Amdocs", aliases: ["Amdocs"], website_domain: "amdocs.com", category: "hitech" },
  { name_he: "אמזון ישראל", name_en: "Amazon Israel", aliases: ["Amazon", "AWS Israel", "אמזון", "AWS"], website_domain: "amazon.jobs", category: "hitech" },
  { name_he: "אמן מחשבים", name_en: "Aman Group", aliases: ["קבוצת אמן", "Aman Computers"], website_domain: "aman.co.il", category: "hitech" },
  { name_he: "אנבידיה ישראל", name_en: "NVIDIA Israel", aliases: ["Nvidia", "אנבידיה"], website_domain: "nvidia.com", category: "hitech" },
  { name_he: "אסם נסטלה", name_en: "Osem Nestle", aliases: ["אסם", "Osem", "Nestle"], website_domain: "osem-nestle.co.il", category: "other" },
  { name_he: "אפל ישראל", name_en: "Apple Israel", aliases: ["Apple", "אפל"], website_domain: "apple.com", category: "hitech" },
  { name_he: "אפלייד מטיריאלס", name_en: "Applied Materials", aliases: ["Applied Materials Israel", "אפלייד"], website_domain: "appliedmaterials.com", category: "hitech" },
  { name_he: "אפספלייר", name_en: "AppsFlyer", aliases: ["AppsFlyer"], website_domain: "appsflyer.com", category: "hitech" },
  { name_he: "אפקה המכללה להנדסה", name_en: "Afeka College of Engineering", aliases: ["אפקה", "Afeka"], website_domain: "afeka.ac.il", category: "education" },
  { name_he: "אקווה סקיוריטי", name_en: "Aqua Security", aliases: ["Aqua Security", "Aqua"], website_domain: "aquasec.com", category: "hitech" },
  { name_he: "אקסוניוס", name_en: "Axonius", aliases: ["Axonius"], website_domain: "axonius.com", category: "hitech" },
  { name_he: "אקסטרה הופ", name_en: "ExtraHop", aliases: ["ExtraHop"], website_domain: "extrahop.com", category: "hitech" },
  { name_he: "אקרו נדלן", name_en: "Acro Real Estate", aliases: ["Acro"], website_domain: "acro.co.il", category: "other" },
  { name_he: "ארגון לתת", name_en: "Latet Organization", aliases: ["לתת", "Latet"], website_domain: "latet.org.il", category: "other" },
  { name_he: "ארליסנס", name_en: "EarlySense", aliases: ["EarlySense"], website_domain: "earlysense.com", category: "health" },
  { name_he: "ארקיע", name_en: "Arkia", aliases: ["Arkia Israeli Airlines"], website_domain: "arkia.co.il", category: "other" },
  { name_he: "בזק", name_en: "Bezeq", aliases: ["Bezeq"], website_domain: "bezeq.co.il", category: "other" },
  { name_he: "בזק בינלאומי", name_en: "Bezeq International", aliases: ["Bezeq International"], website_domain: "bezeqint.net", category: "hitech", parent_name_he: "בזק" },
  { name_he: "ביג מרכזי קניות", name_en: "BIG Shopping Centers", aliases: ["BIG"], website_domain: "bigcenters.co.il", category: "other" },
  { name_he: "ביגפנדה", name_en: "BigPanda", aliases: ["BigPanda"], website_domain: "bigpanda.io", category: "hitech" },
  { name_he: "ביו-סנס וובסטר", name_en: "Biosense Webster", aliases: ["Biosense Webster", "Johnson & Johnson Biosense"], website_domain: "jnjmedtech.com", category: "health" },
  { name_he: "ביוורד", name_en: "BeAware", aliases: [], website_domain: "", category: "other", uncertain_domain: true },
  { name_he: "בינת תקשורת", name_en: "Bynet Data Communications", aliases: ["קבוצת רד-בינת", "Bynet", "בינת"], website_domain: "bynet.co.il", category: "hitech" },
  { name_he: "בנק דיסקונט", name_en: "Discount Bank", aliases: ["דיסקונט", "Discount"], website_domain: "discountbank.co.il", category: "banking" },
  { name_he: "בנק הפועלים", name_en: "Bank Hapoalim", aliases: ["הפועלים", "Hapoalim"], website_domain: "bankhapoalim.co.il", category: "banking" },
  { name_he: "בנק לאומי", name_en: "Bank Leumi", aliases: ["לאומי", "Leumi"], website_domain: "leumi.co.il", category: "banking" },
  { name_he: "בנק מזרחי טפחות", name_en: "Mizrahi Tefahot Bank", aliases: ["מזרחי טפחות", "Mizrahi Tefahot"], website_domain: "mizrahi-tefahot.co.il", category: "banking" },
  { name_he: "גוגל ישראל", name_en: "Google Israel", aliases: ["Google", "גוגל"], website_domain: "google.com", category: "hitech" },
  { name_he: "גוינט ישראל", name_en: "JDC Israel", aliases: ["JDC", "ג'וינט"], website_domain: "jdc.org.il", category: "other" },
  { name_he: "גונג", name_en: "Gong.io", aliases: ["Gong"], website_domain: "gong.io", category: "hitech" },
  { name_he: "גזית גלוב", name_en: "Gazit Globe", aliases: ["G City"], website_domain: "g-city.com", category: "other" },
  { name_he: "גיוון אימגינג", name_en: "Given Imaging", aliases: ["Given Imaging", "Medtronic Given"], website_domain: "medtronic.com", category: "health", parent_name_he: "מדיטרוניק ישראל" },
  { name_he: "גייפרוג", name_en: "JFrog", aliases: ["JFrog"], website_domain: "jfrog.com", category: "hitech" },
  { name_he: "גילת רשתות לוויין", name_en: "Gilat Satellite Networks", aliases: ["Gilat", "גילת"], website_domain: "gilat.com", category: "hitech" },
  { name_he: "גנרל אלקטריק ישראל", name_en: "General Electric Israel", aliases: ["GE", "ג'נרל אלקטריק", "GE Healthcare"], website_domain: "ge.com", category: "hitech" },
  { name_he: "דאטהריילס", name_en: "Datarails", aliases: ["DataRails"], website_domain: "datarails.com", category: "hitech" },
  { name_he: "דואר ישראל", name_en: "Israel Post", aliases: ["דואר", "Israel Post"], website_domain: "israelpost.co.il", category: "government" },
  { name_he: "די אס פי גרופ", name_en: "DSP Group", aliases: ["DSP Group", "Synaptics DSP"], website_domain: "synaptics.com", category: "hitech" },
  { name_he: "דינמיק יילד", name_en: "Dynamic Yield", aliases: ["Dynamic Yield", "Mastercard Dynamic Yield"], website_domain: "dynamicyield.com", category: "hitech" },
  { name_he: "דל ישראל", name_en: "Dell Israel", aliases: ["Dell Technologies", "Dell", "דל"], website_domain: "dell.com", category: "hitech" },
  { name_he: "דן חברת תחבורה", name_en: "Dan Bus Company", aliases: ["דן", "Dan"], website_domain: "dan.co.il", category: "other" },
  { name_he: "דנאל", name_en: "Danel Group", aliases: ["קבוצת דנאל", "Danel"], website_domain: "danel.co.il", category: "other" },
  { name_he: "דניה סיבוס", name_en: "Danya Cebus", aliases: ["Danya Cebus"], website_domain: "danya-cebus.co.il", category: "other" },
  { name_he: "האוניברסיטה העברית", name_en: "Hebrew University of Jerusalem", aliases: ["HUJI", "העברית"], website_domain: "huji.ac.il", category: "education" },
  { name_he: "האוניברסיטה הפתוחה", name_en: "Open University of Israel", aliases: ["Open University", "הפתוחה"], website_domain: "openu.ac.il", category: "education" },
  { name_he: "הבנק הבינלאומי", name_en: "First International Bank of Israel", aliases: ["FIBI", "הבינלאומי"], website_domain: "fibi.co.il", category: "banking" },
  { name_he: "הוט", name_en: "HOT Telecommunication", aliases: ["HOT", "הוט טלקום"], website_domain: "hot.net.il", category: "other" },
  { name_he: "החברה המרכזית למשקאות (קוקה קולה)", name_en: "Central Bottling Company (Coca-Cola Israel)", aliases: ["CBC Group", "קוקה קולה ישראל", "Coca-Cola"], website_domain: "cocacola.co.il", category: "other" },
  { name_he: "הטכניון", name_en: "Technion", aliases: ["Technion - Israel Institute of Technology"], website_domain: "technion.ac.il", category: "education" },
  { name_he: "הייבוב (Hibob)", name_en: "HiBob", aliases: ["HiBob", "Bob", "הייבוב"], website_domain: "hibob.com", category: "hitech" },
  { name_he: "היפו ביטוח", name_en: "Hippo Insurance", aliases: ["Hippo"], website_domain: "hippo.com", category: "hitech" },
  { name_he: "היפראקטיב", name_en: "Hyperactive", aliases: [], website_domain: "", category: "other", uncertain_domain: true },
  { name_he: "המוסד לביטוח לאומי", name_en: "National Insurance Institute", aliases: ["ביטוח לאומי"], website_domain: "btl.gov.il", category: "government" },
  { name_he: "המרכז האקדמי לב (מכון לב)", name_en: "Jerusalem College of Technology (JCT)", aliases: ["JCT", "מכון לב", "מכון נווה", "מכון תל תבונה"], website_domain: "jct.ac.il", category: "education" },
  { name_he: "המרכז הרפואי איכילוב", name_en: "Tel Aviv Sourasky Medical Center (Ichilov)", aliases: ["איכילוב", "Ichilov"], website_domain: "tasmc.org.il", category: "health" },
  { name_he: "המרכז הרפואי הדסה", name_en: "Hadassah Medical Center", aliases: ["הדסה", "Hadassah"], website_domain: "hadassah.org.il", category: "health" },
  { name_he: "המרכז הרפואי שיבא תל השומר", name_en: "Sheba Medical Center", aliases: ["שיבא", "תל השומר", "Sheba"], website_domain: "sheba.co.il", category: "health" },
  { name_he: "הפניקס", name_en: "The Phoenix", aliases: ["Phoenix Insurance", "הפניקס חברה לביטוח"], website_domain: "fnx.co.il", category: "banking" },
  { name_he: "הראל ביטוח", name_en: "Harel Insurance & Finance", aliases: ["הראל", "Harel"], website_domain: "harel-group.co.il", category: "banking" },
  { name_he: "התעשייה האווירית", name_en: "Israel Aerospace Industries", aliases: ["IAI", "תעשייה אווירית"], website_domain: "iai.co.il", category: "hitech" },
  { name_he: "וואן טכנולוגיות", name_en: "ONE Technologies", aliases: ["ONE Software", "וואן"], website_domain: "one1.co.il", category: "hitech" },
  { name_he: "וויז (Wiz)", name_en: "Wiz", aliases: ["Wiz.io", "וויז"], website_domain: "wiz.io", category: "hitech" },
  { name_he: "וויקס", name_en: "Wix.com", aliases: ["Wix", "וויקס"], website_domain: "wix.com", category: "hitech" },
  { name_he: "ווסטרן דיגיטל", name_en: "Western Digital Israel", aliases: ["Western Digital", "SanDisk", "סאנדיסק"], website_domain: "westerndigital.com", category: "hitech" },
  { name_he: "ווקמי", name_en: "WalkMe", aliases: ["WalkMe", "SAP WalkMe"], website_domain: "walkme.com", category: "hitech" },
  { name_he: "ויזה כאל", name_en: "ICC Cal", aliases: ["כאל", "Cal", "כרטיסי אשראי לישראל"], website_domain: "cal-online.co.il", category: "banking" },
];
